=== adrianmlc/DTDs/DTD-6/6_1c.dtd
<!ELEMENT cd (songs, fecha)>
<!ELEMENT songs (song+)>
<!ELEMENT song (title, composers, producers, publisher, artists)>
<!ELEMENT fecha EMPTY>
<!ELEMENT title (#PCDATA)>
<!ELEMENT composers (composer+)>
<!ELEMENT composer (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT producers (producer+)>
<!ELEMENT producer (nombre, apellidos)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT artists (artist+)>
<!ELEMENT artist (#PCDATA)>
<!ATTLIST cd titulo CDATA "title">
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anio CDATA #REQUIRED>
<!ATTLIST song length CDATA #IMPLIED>
<!ATTLIST song anio CDATA #REQUIRED>

=== adrianmlc/DTDs/DTD-6/6_1c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "6_1c.dtd">

<cd>
<songs>
<song anio="1992">
<title>Mi carro me lo robaron</title>
<composers>
<composer>
<nombre>Alfredo</nombre>
<apellidos>Cañas del Rio</apellidos>
</composer>
</composers>
<producers>
<producer>
<nombre>Los del Rio</nombre>
<apellidos>Del rio Profundo</apellidos>
</producer>
</producers>
<publisher>Topete</publisher>
<artists>
<artist>Estopa</artist>
</artists>
</song>
</songs>
<fecha dia="25" mes="Abril" anio="1993"/>
</cd>
