=== adrianmlc/DTDs/DTD-6/6_3.dtd
<!ELEMENT alumnos (alumno)*>
<!ELEMENT alumno (nombre, apellidos, edad?, direccion?, nota, comentario)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT direccion (calle, numero, piso, poblacion, codigo-postal)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT codigo-postal (#PCDATA)>
<!ATTLIST alumno DNI CDATA #REQUIRED>

=== adrianmlc/DTDs/DTD-6/6_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumno SYSTEM "6_3.dtd">

<alumno DNI="11112222A">
<nombre>Adrian Miguel</nombre>
<apellidos>Lopez Casanueva</apellidos>
<edad>23</edad>
<direccion>
<calle>Camino de Rubin</calle>
<numero>15</numero>
<piso>1</piso>
<poblacion>Gijon</poblacion>
<codigo-postal>33213</codigo-postal>
</direccion>
<nota>10</nota>
<comentario>Excelente estudiante</comentario>
</alumno>
