<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaFutbol [
<!ELEMENT ligaFutbol (partido)*>
<!ELEMENT partido (local, visitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ATTLIST partido golesLocal CDATA #REQUIRED>
<!ATTLIST partido golesVisitante CDATA #REQUIRED>
]>

<ligaFutbol>
<partido golesLocal="0" golesVisitante="1">
<local>Nottingham Presa</local>
<visitante>Inter de Mitente</visitante>
</partido>
<partido golesLocal="3" golesVisitante="3">
<local>Vodka Juniors</local>
<visitante>Sparta de Risa</visitante>
</partido>
<partido golesLocal="4" golesVisitante="2">
<local>Water de Munich</local>
<visitante>Esteaua es el grifo</visitante>
</partido>
</ligaFutbol>